import Head from "next/head";
import { Container, Button, Typography } from "@mui/material";

export default function Home({ accessToken }) {
  console.log(accessToken);
  return (
    <>
      <Container>
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        <Button variant='outlined'>Get Access Token !</Button>
        <Typography>{accessToken.access_token}</Typography>
      </Container>
    </>
  );
}

Home.getInitialProps = async (ctx) => {
  const URL = "http://127.0.0.1:5000/login";
  const body = {
    username: "Gladson",
    password: "test123",
  };

  const res = await fetch(URL, {
    method: "POST",
    body: JSON.stringify(body),
  });

  const data = await res.json();
  return { accessToken: data };
};
